In [1]:
import pandas as pd
import numpy as np
import math
import os
import glob

In [38]:
#station data
weather_station = pd.read_csv("../Original_Data/Final_weather_data/Station_list/station_list.txt",delimiter='|')
weather_table = weather_station[['WBAN','State','Latitude','Longitude']]
weather_table.head()

   WBAN State  Latitude  Longitude
0  3011    CO    37.954   -107.901
1  3012    NM    36.458   -105.667
2  3013    CO    38.070   -102.688
3  3014    NM    35.789   -107.248
4  3016    CO    39.526   -107.726

dailyavg0811 = pd.read_csv("../Original_Data/Final_weather_data/More/200811monthly.txt")
result_data = dailyavg0811.rename(columns = {'Wban Number':'WBAN'}).iloc[:,[0,1,6,26,-3]]
final_weather_table = pd.merge(left=weather_table,right=result_data, how='left', left_on='WBAN', right_on='WBAN')
final_weather_table.columns = ['WBAN','State','Latitude','Longitude','YYMM','AvgTemp','TotalMonthlyPrecip','Avgwindspeed']
final_weather_table = final_weather_table[['YYMM','State','WBAN','Latitude','Longitude','AvgTemp','TotalMonthlyPrecip','Avgwindspeed']]
final_weather_table

In [55]:
path =r'../Original_Data/Final_weather_data/More'
allFiles = glob.glob(path + "/*.txt")
weather_frame07to16 = pd.DataFrame()
list07to16_ = []
for file_ in allFiles:
    read_in = pd.read_csv(file_, index_col=None, header=0, error_bad_lines=False)
    result_data = read_in.rename(columns = {'Wban Number':'WBAN'}).iloc[:,[0,1,6,26,-3]]
    final_weather_table = pd.merge(left=weather_table,right=result_data, how='left', left_on='WBAN', right_on='WBAN')
    final_weather_table.columns = ['WBAN','State','Latitude','Longitude','YYMM','AvgTemp','TotalMonthlyPrecip','Avgwindspeed']
    final_weather_table = final_weather_table[['YYMM','State','WBAN','Latitude','Longitude','AvgTemp','TotalMonthlyPrecip','Avgwindspeed']]
    list07to16_.append(final_weather_table)
weather_frame07to16 = pd.concat(list07to16_)
weather_frame07to16

,YYMM,State,WBAN,Latitude,Longitude,AvgTemp,TotalMonthlyPrecip,Avgwindspeed
0,NaN,CO,3011,37.954,-107.901,NaN,NaN,NaN
1,NaN,NM,3012,36.458,-105.667,NaN,NaN,NaN
2,200707.0,CO,3013,38.070,-102.688,M,0.97,8.8
3,NaN,NM,3014,35.789,-107.248,NaN,NaN,NaN
4,200707.0,CO,3016,39.526,-107.726,M,0.26,5.6
5,200707.0,CO,3017,39.833,-104.658,M,0.43,8.6
6,200707.0,TX,3024,35.700,-101.394,M,1.85,8.4
7,200707.0,CO,3026,39.245,-102.284,M,2.55,11.0
8,200707.0,NM,3027,35.003,-105.663,M,2.05,8.5
9,200707.0,CO,3028,37.283,-102.614,M,0.69,10.4
10,200707.0,AZ,3029,35.658,-109.061,M,2.23,4.7
11,200707.0,OK,3030,36.682,-101.505,M,1.20,9.2
12,200707.0,TX,3031,31.921,-102.387,M,1.72,8.1
13,200707.0,TX,3032,30.048,-102.213,M,1.99,8.4
14,NaN,NM,3033,34.985,-106.000,NaN,NaN,NaN
15,NaN,NM,3034,35.145,-106.784,NaN,NaN,NaN
16,NaN,NM,3035,32.853,-104.467,NaN,NaN,NaN
17,NaN,UT,3036,37.583,-109.583,NaN,NaN,NaN
18,NaN,KS,3037,39.428,-101.034,NaN,NaN,NaN
19,NaN,CO,3038,39.467,-106.150,NaN,NaN,NaN
20,NaN,CO,3039,37.450,-106.800,NaN,NaN,NaN
21,NaN,CO,3040,39.217,-104.633,NaN,NaN,NaN
22,NaN,CO,3041,38.483,-106.317,NaN,NaN,NaN
23,NaN,CO,3042,37.500,-105.167,NaN,NaN,NaN
24,NaN,KS,3043,39.840,-101.042,NaN,NaN,NaN
25,NaN,TX,3044,32.213,-101.521,NaN,NaN,NaN
26,NaN,TX,3045,36.414,-100.750,NaN,NaN,NaN
27,NaN,TX,3047,31.622,-102.807,NaN,NaN,NaN
28,NaN,NM,3048,34.356,-106.886,NaN,NaN,NaN
29,NaN,TX,3049,30.384,-103.684,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2249,201612.0,MN,94964,47.822,-91.818,M,M,M
2250,201612.0,MN,94966,46.289,-96.151,M,M,M
2251,201612.0,MN,94967,46.901,-95.068,M,M,10.9
2252,201612.0,MN,94968,43.681,-93.367,M,M,M
2253,201612.0,MN,94969,44.325,-93.301,M,M,M
2254,201612.0,IA,94971,43.408,-94.746,M,M,15.2
2255,201612.0,WI,94973,46.026,-91.444,M,M,7.3
2256,201612.0,MN,94974,45.145,-93.201,M,M,M
2257,201612.0,NE,94975,42.579,-99.984,M,M,M
2258,201612.0,MN,94976,44.450,-95.817,M,M,M
2259,201612.0,MN,94977,48.266,-92.483,M,M,M
2260,201612.0,NE,94978,41.764,-96.178,M,M,11.6
2261,201612.0,IA,94979,41.831,-90.318,M,M,M
2262,201612.0,IA,94982,41.614,-90.591,M,M,12.6
2263,201612.0,WI,94985,44.637,-90.189,M,M,11.3
2264,NaN,MI,94986,45.126,-87.634,NaN,NaN,NaN
2265,201612.0,IA,94988,42.113,-92.918,23.4,0.93,12.6
2266,201612.0,IA,94989,41.992,-93.622,24.7,1.33,11.4
2267,201612.0,SD,94990,43.390,-99.842,M,M,13.7
2268,201612.0,IA,94991,40.633,-93.902,26.5,1.47,10.6
2269,201612.0,MN,94992,47.747,-90.344,M,M,8.9
2270,201612.0,SD,94993,45.669,-96.991,M,M,15.2
2271,201612.0,WI,94994,43.156,-90.678,M,M,6.5
2272,201612.0,NE,94995,40.848,-96.565,26.2,1.32,M
2273,201612.0,NE,94996,40.695,-96.854,26.5,1.38,M
2274,201612.0,MN,94997,46.447,-95.201,M,M,M
2275,201612.0,IA,94998,41.701,-94.917,M,M,M
2276,201612.0,MN,94999,46.548,-93.668,M,M,M
2277,201612.0,AK,96401,62.830,-149.913,M,M,M
2278,NaN,AK,96402,61.731,-148.928,NaN,NaN,NaN