In [42]:
import pandas as pd
import numpy as np

In [43]:
weather_total = pd.read_csv('final_weather_table.txt',low_memory=False)
weather_total.head()

,Unnamed: 0,YYMM,State,WBAN,Latitude,Longitude,AvgTemp,TotalMonthlyPrecip,Avgwindspeed
0,0,199607,AK,25704,51.883,-176.650,51.6,0.22,NaN
1,1,199607,AL,13894,30.688,-88.246,81.7,4.95,5.6
2,2,199607,AL,13895,32.301,-86.394,80.8,8.72,4.8
3,3,199607,AL,3856,34.644,-86.786,78.2,4.7,5.6
4,4,199607,AR,13964,35.334,-94.365,79.7,7.67,5.3

In [44]:
#WindSpeed
windspeed = weather_total.iloc[:,[1,2,3,-1]]
windspeed.replace('M',np.nan,inplace=True)
windspeed.dropna(inplace=True)
windspeed.head(10)

C:\Users\Jiayuan\Miniconda3\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
C:\Users\Jiayuan\Miniconda3\lib\site-packages\ipykernel\__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

      YYMM State   WBAN Avgwindspeed
1   199607    AL  13894          5.6
2   199607    AL  13895          4.8
3   199607    AL   3856          5.6
4   199607    AR  13964          5.3
5   199607    AZ  93167         10.7
6   199607    AZ   3103          5.2
7   199607    AZ   3145          9.8
9   199607    AZ  23194          8.1
10  199607    AZ  23160          7.6
11  199607    AZ  23183          6.7

In [7]:
#revise the type of columns
windspeed['YYMM'] = windspeed['YYMM'].astype(str)
windspeed['Avgwindspeed'] = windspeed['Avgwindspeed'].astype(float)

C:\Users\Jiayuan\Miniconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\Users\Jiayuan\Miniconda3\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [28]:
#for loop for all 51 states
statelist = ['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 
             'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 
             'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 
             'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY']
state_total = pd.DataFrame()

#Run for all 51 states
for item in statelist:
    name = item #remain the name of state as str
    item = windspeed[windspeed['State'].isin([item])] #extract dataframe of a specific state
    
    #for all the year in a specific state

    item.reset_index(inplace=True)
    item = item.iloc[:,1:]

    year_list = ['1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006',
                '2007','2008','2009','2010','2011','2012','2013','2014','2015','2016']
    avg_list = []
    avg_windspeed = pd.DataFrame()
    for i in year_list:
        year = item[item['YYMM'].str.contains(i)]#find all the data in a specific year
        avg = sum(list(year['Avgwindspeed']))/len(list(year['Avgwindspeed']))
        avg_list.append(avg)

    #Create a list of state containing 21 items of AZ
    state = pd.Series(np.zeros(21))
    state.replace('0.0',name,inplace=True)

    avg_windspeed['State'] = state
    avg_windspeed['Year'] = year_list
    avg_windspeed['Avgwindspeed'] = avg_list
    
    state_total = state_total.append(avg_windspeed,ignore_index=True)

In [31]:
state_total.to_csv('state_total_windspeed.csv')

In [45]:
#Precip
precip = weather_total.iloc[:,[1,2,3,-2]]
precip.replace('M',np.nan,inplace=True)
precip.replace('T','0.0',inplace=True)
precip.dropna(inplace=True)
precip.head(20)

C:\Users\Jiayuan\Miniconda3\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
C:\Users\Jiayuan\Miniconda3\lib\site-packages\ipykernel\__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Jiayuan\Miniconda3\lib\site-packages\ipykernel\__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

      YYMM State   WBAN TotalMonthlyPrecip
0   199607    AK  25704               0.22
1   199607    AL  13894               4.95
2   199607    AL  13895               8.72
3   199607    AL   3856                4.7
4   199607    AR  13964               7.67
5   199607    AZ  93167               1.69
6   199607    AZ   3103               1.79
7   199607    AZ   3145               0.12
8   199607    AZ   3195               1.09
9   199607    AZ  23194                0.0
10  199607    AZ  23160               1.88
11  199607    AZ  23183               0.58
12  199607    CA  93193                0.0
13  199607    CA  23155                0.0
14  199607    CA  23157                0.0
15  199607    CA  23187                0.0
16  199607    CA  24257               0.33
17  199607    CA  93115                0.0
18  199607    CA  23225                0.0
21  199607    CA  24216                0.0

In [47]:
#revise the type of columns
precip['YYMM'] = precip['YYMM'].astype(str)
precip['TotalMonthlyPrecip'] = precip['TotalMonthlyPrecip'].astype(float)

C:\Users\Jiayuan\Miniconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\Users\Jiayuan\Miniconda3\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [49]:
#for loop for all 51 states
statelist = ['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 
             'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 
             'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 
             'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY']
state_total_precip = pd.DataFrame()

#Run for all 51 states
for item in statelist:
    name = item #remain the name of state as str
    item = precip[precip['State'].isin([item])] #extract dataframe of a specific state
    
    #for all the year in a specific state

    item.reset_index(inplace=True)
    item = item.iloc[:,1:]

    year_list = ['1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006',
                '2007','2008','2009','2010','2011','2012','2013','2014','2015','2016']
    avg_list = []
    avg_precip = pd.DataFrame()
    for i in year_list:
        year = item[item['YYMM'].str.contains(i)]#find all the data in a specific year
        avg = sum(list(year['TotalMonthlyPrecip']))/len(list(year['TotalMonthlyPrecip']))
        avg_list.append(avg)

    #Create a list of state containing 21 items of AZ
    state = pd.Series(np.zeros(21))
    state.replace('0.0',name,inplace=True)

    avg_precip['State'] = state
    avg_precip['Year'] = year_list
    avg_precip['Avgwindspeed'] = avg_list
    
    state_total_precip = state_total_precip.append(avg_precip,ignore_index=True)

In [51]:
state_total_precip.to_csv('state_total_precip.csv')

#for all the year in a specific state

#extract one state and reset index
AZ = windspeed[windspeed['State'].isin(['AZ'])]
AZ.reset_index(inplace=True)
AZ = AZ.iloc[:,1:]

year_list = ['1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006',
            '2007','2008','2009','2010','2011','2012','2013','2014','2015','2016']
avg_list = []
avg_windspeed = pd.DataFrame()
for i in year_list:
    year = AZ[AZ['YYMM'].str.contains(i)]#find all the data in a specific year
    avg = sum(list(year['Avgwindspeed']))/len(list(year['Avgwindspeed']))
    avg_list.append(avg)

#Create a list of state containing 21 items of AZ
state = pd.Series(np.zeros(21))
state.replace('0.0','AZ',inplace=True)

avg_windspeed['State'] = state
avg_windspeed['Year'] = year_list
avg_windspeed['Avgwindspeed'] = avg_list