In [1]:
import pandas as pd
import itertools as it
import numpy as np

In [2]:
data = pd.read_csv('../Original_Data/annual_generation_source_state.csv')

In [3]:
data = data.drop(['Unnamed: 4','Unnamed: 5','Unnamed: 6','Unnamed: 7','Unnamed: 8','Unnamed: 9'],axis = 1)

In [4]:
data = data[data.STATE != '  ']
data = data[data.STATE != 'US-TOTAL']
data = data[data.STATE != 'US-Total']

In [5]:
data

       YEAR STATE                ENERGY SOURCE GENERATION (Megawatthours)
0      1990    AK                        Total                  5,599,506
1      1990    AK                         Coal                    510,573
2      1990    AK   Hydroelectric Conventional                    974,521
3      1990    AK                  Natural Gas                  3,466,261
4      1990    AK                    Petroleum                    497,116
5      1990    AK                         Wind                          0
6      1990    AK  Wood and Wood Derived Fuels                    151,035
7      1990    AK                        Total                  4,493,024
8      1990    AK                         Coal                    311,960
9      1990    AK   Hydroelectric Conventional                    974,521
10     1990    AK                  Natural Gas                  2,869,638
11     1990    AK                    Petroleum                    336,905
12     1990    AK                         Wind                          0
13     1990    AK                        Total                    840,949
14     1990    AK                  Natural Gas                    596,623
15     1990    AK                    Petroleum                     93,291
16     1990    AK  Wood and Wood Derived Fuels                    151,035
17     1990    AK                        Total                    265,533
18     1990    AK                         Coal                    198,613
19     1990    AK                    Petroleum                     66,920
20     1990    AL                        Total                 79,652,133
21     1990    AL                         Coal                 53,658,115
22     1990    AL   Hydroelectric Conventional                 10,366,507
23     1990    AL                  Natural Gas                  1,020,714
24     1990    AL                      Nuclear                 12,051,882
25     1990    AL                Other Biomass                     47,503
26     1990    AL                  Other Gases                    269,476
27     1990    AL                    Petroleum                    138,089
28     1990    AL  Wood and Wood Derived Fuels                  2,099,847
29     1990    AL                        Total                     27,936
...     ...   ...                          ...                        ...
45320  2015    WV                         Coal                 56,309,986
45321  2015    WV   Hydroelectric Conventional                    487,375
45322  2015    WV                  Natural Gas                    118,608
45323  2015    WV                        Other                          0
45324  2015    WV                    Petroleum                    126,533
45325  2015    WY                        Total                 48,966,519
45326  2015    WY                         Coal                 43,091,189
45327  2015    WY   Hydroelectric Conventional                    868,261
45328  2015    WY                  Natural Gas                    722,304
45329  2015    WY                  Other Gases                    405,386
45330  2015    WY                        Other                     77,772
45331  2015    WY                    Petroleum                     44,898
45332  2015    WY                         Wind                  3,756,708
45333  2015    WY                        Total                  1,485,541
45334  2015    WY                         Coal                    419,827
45335  2015    WY                  Natural Gas                    582,192
45336  2015    WY                  Other Gases                    405,386
45337  2015    WY                        Other                     77,772
45338  2015    WY                    Petroleum                        364
45339  2015    WY                        Total                  2,693,131
45340  2015    WY                         Coal                    733,913
45341  2015    WY   Hydroelectric Conventional                      9,908
45342  2015    WY                  Natural Gas                        640
45343  2015    WY                         Wind                  1,948,670
45344  2015    WY                        Total                 44,787,847
45345  2015    WY                         Coal                 41,937,449
45346  2015    WY   Hydroelectric Conventional                    858,353
45347  2015    WY                  Natural Gas                    139,473
45348  2015    WY                    Petroleum                     44,535
45349  2015    WY                         Wind                  1,808,038

[43596 rows x 4 columns]

In [6]:
yearlist = []
for key, group in it.groupby(sorted(data.YEAR)):
    yearlist.append(key)
print(yearlist)

[1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015]

In [7]:
statelist = []
for key, group in it.groupby(sorted(data.STATE)):
    statelist.append(key)
print(statelist)

['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY']

In [8]:
esourcelist = []
for key, group in it.groupby(sorted(data['ENERGY SOURCE'])):
    esourcelist.append(key)
print(esourcelist)

['Coal', 'Geothermal', 'Hydroelectric Conventional', 'Natural Gas', 'Nuclear', 'Other', 'Other Biomass', 'Other Gases', 'Petroleum', 'Pumped Storage', 'Solar Thermal and Photovoltaic', 'Total', 'Wind', 'Wood and Wood Derived Fuels']

In [14]:
arrangedata = pd.DataFrame(index = np.arange(len(yearlist)*len(statelist)),columns = (['Year','State'] + esourcelist))
year = []
for i in yearlist:
    year += list(np.full(len(statelist),i,dtype = int))
arrangedata.Year = year
state = []
for i in range(len(yearlist)):
    state += statelist
arrangedata.State = state

In [15]:
arrangedata

,Year,State,Coal,Geothermal,Hydroelectric Conventional,Natural Gas,Nuclear,Other,Other Biomass,Other Gases,Petroleum,Pumped Storage,Solar Thermal and Photovoltaic,Total,Wind,Wood and Wood Derived Fuels
0,1990,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1990,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1990,AR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1990,AZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1990,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1990,CO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1990,CT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1990,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1990,DE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1990,FL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1990,GA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1990,HI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1990,IA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1990,ID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1990,IL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1990,IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1990,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1990,KY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1990,LA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1990,MA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1990,MD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1990,ME,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1990,MI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1990,MN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1990,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1990,MS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1990,MT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1990,NC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1990,ND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1990,NE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296,2015,ME,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1297,2015,MI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1298,2015,MN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1299,2015,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1300,2015,MS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1301,2015,MT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1302,2015,NC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1303,2015,ND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1304,2015,NE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1305,2015,NH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1306,2015,NJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1307,2015,NM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1308,2015,NV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1309,2015,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1310,2015,OH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1311,2015,OK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1312,2015,OR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1313,2015,PA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1314,2015,RI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1315,2015,SC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1316,2015,SD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1317,2015,TN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1318,2015,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1319,2015,UT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1320,2015,VA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1321,2015,VT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1322,2015,WA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1323,2015,WI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1324,2015,WV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1325,2015,WY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
for m in range(len(yearlist)*len(statelist)):
    for i in yearlist:
        for j in statelist:
            for k in esourcelist:
                esourcesum = 0
                for l in range(data.shape[0]):
                    if data.loc[l].YEAR == i and data.loc[l].STATE == j and data.loc[l]['ENERGY SOURCE'] == k:
                        esourcesum += int(data.loc[l]['GENERATION (Megawatthours)'].replace(',',''))
                        arrangedata.loc[m]['Year'] = i
                        arrangedata.loc[m]['State'] = j
                        arrangedata.loc[m][k] = esourcesum

KeyError: 'the label [1189] is not in the [index]'

In [ ]:
data.loc[1].YEAR

In [ ]:
data.loc[1]['ENERGY SOURCE']

In [ ]:
int(data.loc[0]['GENERATION (Megawatthours)'].replace(',',''))

In [ ]:
abcd = pd.DataFrame(index = np.arange(len(yearlist)*len(statelist)),columns = (['Year','State'] + esourcelist))

In [ ]:
abcd.loc[1].Year = 1992

In [ ]:
abcd

In [ ]:
len(yearlist)*len(statelist)

In [ ]:
np.arange(len(yearlist)*len(statelist))

In [ ]:
aaa = np.full(3,8,dtype = int)

In [ ]:
bbb = np.full(3,9)

In [ ]:
ccc = list(aaa) + list(bbb)

In [ ]:
print(ccc)